[package]
name = "aoc_utility"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["advent", "aoc", "string", "parse"]
description = "This is Advent of Code Utility for parsing daily input"

[dependencies]
