[package]
name = "aoc_utility"
version = "0.1.3"
edition = "2021"
license = "MIT"
keywords = ["advent", "aoc", "string", "parse"]
description = "This is Advent of Code Utility for parsing daily input"

[dependencies]
ureq = "2.9.7"